### ISSUE TITLE
Error - Configuration File Missing

### ISSUE THREAD

**Issue by isudoi** [nickkjolsing/dockerMullvadVPN#1]
Greetings.

Getting the following error and the container keeps restarting

`ERROR: No configuration file found. Please check your mount and file permissions. Exiting.`

I think I don't have the correct format of the files of the config

Can you please specify which platform/OS and config files you have used for that setup?
1. Choose your platform (Windows - MacOS - Linux .....?)

I tried the following:

![image](https://user-images.githubusercontent.com/5244872/107104970-1232d580-67f2-11eb-956b-60cabd8d81ad.png)

Setup:
Synology NAS - Docker - Portainer 

Example when you select Linux

![image](https://user-images.githubusercontent.com/5244872/107105323-a6516c80-67f3-11eb-95db-ba0fc51bb534.png)

Windows
![image](https://user-images.githubusercontent.com/5244872/107105344-c97c1c00-67f3-11eb-9519-dc9c2a491f78.png)

**Comment by nickkjolsing** [comment]
Hey ansred, 

Sorry for the late response! 

Below is the directory that I keep all config files. I use Ubuntu 18.04 LTS with Docker 20.10.5. All files and directory has permissions 755. 

![Screen Shot 2021-03-28 at 4 29 22 PM](https://user-images.githubusercontent.com/49295025/112768686-c70f9480-8fe2-11eb-8b06-7e1135cec68e.png)
