### ISSUE TITLE
I think there is a mistake in your description

### ISSUE THREAD

**Issue by prutheus** [nickkjolsing/dockerMullvadVPN#2]
Like you have shown with transmission, I have a docker container running mysql ... port 3306
I want to be able to access it - but it is behind the openvnc-client mullvad "gateway"

Si how should I need to configure the ports to access it from the Mullvad-network - assuming that my opened port by mullvad is 54949?

Regards,
Martin

**Comment by nickkjolsing** [comment]
I have the same question unfortunately :( Was just recently trying to accomplish somewhat the same thing, but have not found an answer yet. 

I'm not entirely sure on how the Docker networks should be setup to send outgoing traffic through the VPN container while allowing local inbound traffic from the LAN where the container is deployed. 

Please let me know if you do figure it out

**Comment by ejach** [comment]
I created PR #6 that fixes this issue.
